Update Package.swift
/*/Packages/mysql-swift.git/Package.swift:8:5: error: argument 'targets' must precede argument 'dependencies'
    targets: [
    ^
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.